[instance]
address = "best-friends.chat"
access_token = "replace_something"

[database]
mode = "postgresql"
name = "kotohirayu"
user = "kotohirayu"
pass = "password"
host = "localhost"
port = 5432

[user]
me = "Yu"
god = "YuzuRyo61"

[log]
enable = true

[follow]
condition_rate = 200
exclude = [1136, 1, 2, 4]
down_step = 3

[features]
ngword = true
voteOptout = true
voteOptoutTag = "ユウちゃん見送り投票"

[i18n]
lang = "ja_JP"

[linenotify]
enable = false
token = "replace_something"
