[instance]
address = "best-friends.chat"
access_token = "replace_something"

[user]
me = "Yu"
god = "YuzuRyo61"

[log]
enable = true

[follow]
condition_rate = 200
exclude = [1136, 1, 2, 4]

[i18n]
lang = "ja_JP"

[linenotify]
enable = false
token = "replace_something"

[web]
enable = true
base = "https://yu-console.example.com"
user = "username"
pass = "password"
